services:
  rabbitmq:
    image: rabbitmq:4-management
    ports:
      - 5672:5672 # AMQP port
      - 1883:1883 # MQTT port
      - 15672:15672 # Management UI
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
